import { addDays, format, subDays, subMonths } from "date-fns";
import type { Patient, Visit } from "./types";

function iso(d: Date) {
  return format(d, "yyyy-MM-dd");
}

export function makeSeed(now: Date): { patients: Patient[]; visits: Visit[] } {
  const today = iso(now);
  const patients: Patient[] = [
    {
      id: "pt_okello",
      mrn: "MRRH-DM-01104",
      firstName: "James",
      lastName: "Okello",
      sex: "M",
      dob: "1988-03-12",
      phone: "+256 772 441 208",
      village: "Kakoba",
      district: "Mbarara",
      diagnosis: "t2dm",
      diagnosisYear: 2026,
      riskFactors: ["family-t2dm", "sedentary", "weight-gain"],
      conditions: [],
      allergies: "None known",
      currentMeds: [],
      weightKg: 78,
      heightCm: 172,
      nextReview: today,
      queue: { date: today, stage: "waiting", timeSlot: "08:20", checkInAt: "08:12" },
      labs: { a1c: 11.8, a1cDate: today, fpg: 268, randomBg: 342 },
      hcm: {},
      createdAt: iso(subDays(now, 1)),
    },
    {
      id: "pt_nakato",
      mrn: "MRRH-DM-00881",
      firstName: "Grace",
      lastName: "Nakato",
      sex: "F",
      dob: "1972-07-04",
      phone: "+256 701 553 914",
      village: "Nyamitanga",
      district: "Mbarara",
      diagnosis: "t2dm",
      diagnosisYear: 2018,
      riskFactors: ["family-t2dm", "htn"],
      conditions: [],
      allergies: "None known",
      currentMeds: [
        { name: "Metformin", dose: "1000 mg BID", cls: "metformin" },
        { name: "Glibenclamide", dose: "5 mg daily", cls: "su" },
      ],
      weightKg: 86,
      heightCm: 158,
      nextReview: today,
      queue: { date: today, stage: "waiting", timeSlot: "08:40", checkInAt: "08:28" },
      labs: { a1c: 9.1, a1cDate: iso(subDays(now, 4)), fpg: 178, acr: 22, egfr: 78, ldl: 132 },
      hcm: {
        lastA1c: iso(subDays(now, 4)),
        lastFoot: iso(subMonths(now, 3)),
        lastEye: iso(subMonths(now, 14)),
        lastLipids: iso(subMonths(now, 13)),
        lastAcr: iso(subMonths(now, 11)),
        lastB12: iso(subMonths(now, 20)),
        influenza: iso(subMonths(now, 11)),
      },
      createdAt: iso(subMonths(now, 40)),
    },
    {
      id: "pt_nalubega",
      mrn: "MRRH-DM-00612",
      firstName: "Mary",
      lastName: "Nalubega",
      sex: "F",
      dob: "1963-11-21",
      phone: "+256 782 019 440",
      village: "Ruharo",
      district: "Mbarara",
      diagnosis: "t2dm",
      diagnosisYear: 2014,
      riskFactors: ["htn", "cvd"],
      conditions: ["ckd", "neuropathy"],
      allergies: "None known",
      currentMeds: [
        { name: "Metformin", dose: "500 mg BID", cls: "metformin" },
        { name: "Amlodipine", dose: "10 mg daily", cls: "other" },
      ],
      weightKg: 72,
      heightCm: 160,
      nextReview: today,
      queue: { date: today, stage: "consult", timeSlot: "08:00", checkInAt: "07:48" },
      labs: { a1c: 8.4, a1cDate: iso(subDays(now, 2)), fpg: 154, acr: 180, egfr: 48, ldl: 126 },
      hcm: {
        lastA1c: iso(subDays(now, 2)),
        lastFoot: iso(subMonths(now, 1)),
        lastEye: iso(subMonths(now, 8)),
        lastLipids: iso(subMonths(now, 8)),
        lastAcr: iso(subDays(now, 2)),
        lastEgfr: iso(subDays(now, 2)),
        lastB12: iso(subMonths(now, 6)),
      },
      createdAt: iso(subMonths(now, 90)),
    },
    {
      id: "pt_kizza",
      mrn: "MRRH-DM-00940",
      firstName: "David",
      lastName: "Kizza",
      sex: "M",
      dob: "1979-01-30",
      phone: "+256 774 220 118",
      village: "Kakiika",
      district: "Mbarara",
      diagnosis: "t2dm",
      diagnosisYear: 2019,
      riskFactors: ["family-t2dm", "htn"],
      conditions: [],
      allergies: "None known",
      currentMeds: [
        { name: "Metformin", dose: "1000 mg BID", cls: "metformin" },
        { name: "NPH insulin", dose: "42 U at bedtime", cls: "insulin-basal" },
        { name: "Enalapril", dose: "10 mg daily", cls: "acei" },
      ],
      weightKg: 70,
      heightCm: 174,
      nextReview: today,
      queue: { date: today, stage: "waiting", timeSlot: "09:00", checkInAt: "08:51" },
      labs: { a1c: 8.6, a1cDate: iso(subDays(now, 6)), fpg: 118, ppg: 214, ldl: 96, egfr: 88, acr: 18 },
      hcm: {
        lastA1c: iso(subDays(now, 6)),
        lastFoot: iso(subMonths(now, 2)),
        lastEye: iso(subMonths(now, 10)),
        lastLipids: iso(subMonths(now, 10)),
        lastAcr: iso(subMonths(now, 10)),
        lastB12: iso(subMonths(now, 9)),
      },
      createdAt: iso(subMonths(now, 48)),
    },
    {
      id: "pt_namukasa",
      mrn: "MRRH-DM-00408",
      firstName: "Ruth",
      lastName: "Namukasa",
      sex: "F",
      dob: "1955-05-18",
      phone: "+256 759 883 201",
      village: "Bwizibwera",
      district: "Rwampara",
      diagnosis: "t2dm",
      diagnosisYear: 2011,
      riskFactors: ["htn"],
      conditions: ["esrd", "ckd", "anemia"],
      highHypoRisk: true,
      limitedLifeExpectancy: true,
      allergies: "None known",
      currentMeds: [
        { name: "NPH insulin", dose: "10 U morning", cls: "insulin-basal" },
        { name: "Amlodipine", dose: "5 mg daily", cls: "other" },
      ],
      weightKg: 58,
      heightCm: 154,
      nextReview: today,
      queue: { date: today, stage: "labs", timeSlot: "08:10", checkInAt: "07:55" },
      labs: { a1c: 8.2, a1cDate: iso(subDays(now, 1)), fpg: 142, egfr: 22, acr: 420, ldl: 88 },
      hcm: {
        lastA1c: iso(subDays(now, 1)),
        lastFoot: iso(subMonths(now, 1)),
        lastEye: iso(subMonths(now, 5)),
        lastLipids: iso(subMonths(now, 5)),
        lastAcr: iso(subDays(now, 1)),
        lastEgfr: iso(subDays(now, 1)),
      },
      createdAt: iso(subMonths(now, 120)),
    },
    {
      id: "pt_mugisha",
      mrn: "MRRH-DM-00777",
      firstName: "Peter",
      lastName: "Mugisha",
      sex: "M",
      dob: "1964-09-02",
      phone: "+256 772 990 014",
      village: "Kamukuzi",
      district: "Mbarara",
      diagnosis: "t2dm",
      diagnosisYear: 2016,
      riskFactors: ["htn"],
      conditions: [],
      allergies: "None known",
      currentMeds: [
        { name: "Metformin", dose: "1000 mg BID", cls: "metformin" },
        { name: "Enalapril", dose: "10 mg daily", cls: "acei" },
        { name: "Atorvastatin", dose: "20 mg daily", cls: "statin" },
      ],
      weightKg: 81,
      heightCm: 176,
      nextReview: iso(addDays(now, 160)),
      queue: { date: today, stage: "pharmacy", timeSlot: "07:50", checkInAt: "07:40" },
      labs: { a1c: 6.7, a1cDate: iso(subDays(now, 3)), fpg: 108, ppg: 146, ldl: 84, egfr: 72, acr: 12 },
      hcm: {
        lastA1c: iso(subDays(now, 3)),
        lastFoot: today,
        lastEye: iso(subMonths(now, 7)),
        lastEyeNormal: true,
        lastLipids: iso(subMonths(now, 3)),
        lastAcr: iso(subMonths(now, 3)),
        lastB12: iso(subMonths(now, 4)),
        influenza: iso(subMonths(now, 2)),
        hbvImmune: true,
      },
      createdAt: iso(subMonths(now, 70)),
    },
    {
      id: "pt_atuhaire",
      mrn: "MRRH-DM-01220",
      firstName: "Sarah",
      lastName: "Atuhaire",
      sex: "F",
      dob: "1985-02-14",
      phone: "+256 705 118 632",
      village: "Nyakayojo",
      district: "Mbarara",
      diagnosis: "prediabetes",
      riskFactors: ["gdm-hx", "family-t2dm", "sedentary", "weight-gain"],
      conditions: [],
      allergies: "None known",
      currentMeds: [],
      weightKg: 98,
      heightCm: 162,
      nextReview: today,
      queue: { date: today, stage: "waiting", timeSlot: "09:20", checkInAt: "09:05" },
      labs: { a1c: 6.3, a1cDate: iso(subDays(now, 8)), fpg: 114 },
      hcm: { lastA1c: iso(subDays(now, 8)) },
      createdAt: iso(subDays(now, 8)),
    },
    {
      id: "pt_tumusiime",
      mrn: "MRRH-DM-00551",
      firstName: "John",
      lastName: "Tumusiime",
      sex: "M",
      dob: "1971-12-09",
      phone: "+256 782 441 009",
      village: "Kabwohe",
      district: "Sheema",
      diagnosis: "t2dm",
      diagnosisYear: 2017,
      riskFactors: ["htn", "sedentary"],
      conditions: ["neuropathy", "pvd"],
      allergies: "None known",
      currentMeds: [
        { name: "Metformin", dose: "850 mg BID", cls: "metformin" },
        { name: "Gliclazide", dose: "80 mg daily", cls: "su" },
        { name: "Enalapril", dose: "5 mg daily", cls: "acei" },
      ],
      weightKg: 76,
      heightCm: 168,
      nextReview: today,
      queue: { date: today, stage: "waiting", timeSlot: "09:40" },
      labs: { a1c: 7.4, a1cDate: iso(subMonths(now, 4)), fpg: 136, ldl: 118, egfr: 64, acr: 44 },
      hcm: {
        lastA1c: iso(subMonths(now, 4)),
        lastFoot: iso(subMonths(now, 8)),
        lastEye: "2024-01-18",
        lastLipids: iso(subMonths(now, 16)),
        lastAcr: iso(subMonths(now, 16)),
        lastB12: undefined,
        lastLft: iso(subMonths(now, 18)),
      },
      createdAt: iso(subMonths(now, 60)),
    },
    {
      id: "pt_komugisha",
      mrn: "MRRH-DM-01002",
      firstName: "Hope",
      lastName: "Komugisha",
      sex: "F",
      dob: "1976-08-22",
      phone: "+256 773 220 887",
      village: "Biharwe",
      district: "Mbarara",
      diagnosis: "t2dm",
      diagnosisYear: 2021,
      riskFactors: ["family-t2dm"],
      conditions: [],
      allergies: "None known",
      currentMeds: [
        { name: "Metformin", dose: "1000 mg BID", cls: "metformin" },
        { name: "Atorvastatin", dose: "20 mg daily", cls: "statin" },
      ],
      weightKg: 68,
      heightCm: 161,
      nextReview: iso(addDays(now, 170)),
      queue: { date: today, stage: "done", timeSlot: "07:30", checkInAt: "07:22" },
      labs: { a1c: 7.1, a1cDate: today, fpg: 122, ldl: 90, egfr: 91, acr: 8 },
      hcm: {
        lastA1c: today,
        lastFoot: today,
        lastEye: iso(subMonths(now, 6)),
        lastLipids: today,
        lastAcr: today,
        lastB12: iso(subMonths(now, 2)),
      },
      createdAt: iso(subMonths(now, 36)),
    },
    {
      id: "pt_byaruhanga",
      mrn: "MRRH-DM-00330",
      firstName: "Paul",
      lastName: "Byaruhanga",
      sex: "M",
      dob: "1981-04-11",
      phone: "+256 701 882 441",
      village: "Ishongororo",
      district: "Ibanda",
      diagnosis: "t2dm",
      diagnosisYear: 2020,
      riskFactors: ["family-t2dm"],
      conditions: [],
      allergies: "None known",
      currentMeds: [
        { name: "Metformin", dose: "500 mg BID", cls: "metformin" },
        { name: "Atorvastatin", dose: "20 mg daily", cls: "statin" },
      ],
      weightKg: 74,
      heightCm: 170,
      nextReview: iso(addDays(now, 118)),
      labs: { a1c: 6.9, a1cDate: iso(subMonths(now, 2)), fpg: 104, ldl: 78, egfr: 96, acr: 6 },
      hcm: {
        lastA1c: iso(subMonths(now, 2)),
        lastFoot: iso(subMonths(now, 2)),
        lastEye: iso(subMonths(now, 11)),
        lastLipids: iso(subMonths(now, 2)),
        lastAcr: iso(subMonths(now, 2)),
        lastB12: iso(subMonths(now, 2)),
        influenza: iso(subMonths(now, 4)),
      },
      createdAt: iso(subMonths(now, 42)),
    },
    {
      id: "pt_kyomuhendo",
      mrn: "MRRH-DM-00690",
      firstName: "Alice",
      lastName: "Kyomuhendo",
      sex: "F",
      dob: "1968-06-27",
      phone: "+256 782 110 334",
      village: "Kinoni",
      district: "Rwampara",
      diagnosis: "t2dm",
      diagnosisYear: 2015,
      riskFactors: ["htn"],
      conditions: [],
      allergies: "None known",
      currentMeds: [{ name: "Metformin", dose: "1000 mg BID", cls: "metformin" }],
      weightKg: 80,
      heightCm: 157,
      nextReview: iso(subDays(now, 21)),
      labs: { a1c: 7.6, a1cDate: iso(subMonths(now, 4)), fpg: 140, ldl: 110, egfr: 70, acr: 28 },
      hcm: {
        lastA1c: iso(subMonths(now, 4)),
        lastFoot: iso(subMonths(now, 4)),
        lastEye: iso(subMonths(now, 15)),
        lastLipids: iso(subMonths(now, 15)),
        lastAcr: iso(subMonths(now, 15)),
      },
      createdAt: iso(subMonths(now, 80)),
    },
    {
      id: "pt_wasswa",
      mrn: "MRRH-DM-00802",
      firstName: "Emmanuel",
      lastName: "Wasswa",
      sex: "M",
      dob: "1975-10-03",
      phone: "+256 774 009 221",
      village: "Nansana-outreach",
      district: "Isingiro",
      diagnosis: "t2dm",
      diagnosisYear: 2022,
      riskFactors: ["family-t2dm", "htn"],
      conditions: [],
      allergies: "None known",
      currentMeds: [
        { name: "Metformin", dose: "1000 mg BID", cls: "metformin" },
        { name: "Gliclazide", dose: "80 mg daily", cls: "su" },
        { name: "Enalapril", dose: "10 mg daily", cls: "acei" },
      ],
      weightKg: 84,
      heightCm: 178,
      nextReview: iso(addDays(now, 12)),
      labs: { a1c: 7.9, a1cDate: iso(subDays(now, 18)), fpg: 148, ldl: 102, egfr: 81, acr: 16 },
      hcm: {
        lastA1c: iso(subDays(now, 18)),
        lastFoot: iso(subDays(now, 18)),
        lastEye: iso(subMonths(now, 9)),
        lastLipids: iso(subMonths(now, 9)),
        lastAcr: iso(subMonths(now, 9)),
        lastB12: iso(subMonths(now, 9)),
      },
      createdAt: iso(subMonths(now, 28)),
    },
    {
      id: "pt_asiimwe",
      mrn: "MRRH-DM-01410",
      firstName: "Faith",
      lastName: "Asiimwe",
      sex: "F",
      dob: "1997-01-19",
      phone: "+256 705 667 190",
      village: "Kakiika",
      district: "Mbarara",
      diagnosis: "screening",
      riskFactors: ["family-t2dm", "sedentary"],
      conditions: [],
      allergies: "None known",
      currentMeds: [],
      weightKg: 74,
      heightCm: 165,
      nextReview: iso(addDays(now, 350)),
      labs: { a1c: 5.4, a1cDate: iso(subDays(now, 20)), fpg: 92 },
      hcm: { lastA1c: iso(subDays(now, 20)) },
      createdAt: iso(subDays(now, 20)),
    },
    {
      id: "pt_mwesigwa",
      mrn: "MRRH-DM-00218",
      firstName: "Robert",
      lastName: "Mwesigwa",
      sex: "M",
      dob: "1960-02-08",
      phone: "+256 772 331 045",
      village: "Rugando",
      district: "Ntungamo",
      diagnosis: "t2dm",
      diagnosisYear: 2012,
      riskFactors: ["htn", "cvd"],
      conditions: ["cvd"],
      allergies: "None known",
      currentMeds: [
        { name: "Metformin", dose: "1000 mg BID", cls: "metformin" },
        { name: "Enalapril", dose: "20 mg daily", cls: "acei" },
        { name: "Aspirin", dose: "75 mg daily", cls: "other" },
      ],
      weightKg: 79,
      heightCm: 171,
      nextReview: iso(subDays(now, 5)),
      labs: { a1c: 7.8, a1cDate: iso(subMonths(now, 3)), fpg: 138, ldl: 118, egfr: 58, acr: 52 },
      hcm: {
        lastA1c: iso(subMonths(now, 3)),
        lastFoot: iso(subMonths(now, 3)),
        lastEye: iso(subMonths(now, 12)),
        lastLipids: iso(subMonths(now, 14)),
        lastAcr: iso(subMonths(now, 3)),
        lastB12: iso(subMonths(now, 14)),
      },
      createdAt: iso(subMonths(now, 110)),
    },
  ];

  const visits: Visit[] = [
    visit("vis_nakato_1", "pt_nakato", subMonths(now, 9), 8.4, 152, "Dr. Atwine", "Metformin titrated to 1 g BID."),
    visit("vis_nakato_2", "pt_nakato", subMonths(now, 6), 8.8, 164, "Dr. Namanya", "Added glibenclamide 5 mg. Adherence fair."),
    visit("vis_nakato_3", "pt_nakato", subMonths(now, 3), 9.1, 178, "Dr. Atwine", "A1c rising on two orals. Discuss insulin next visit."),
    visit("vis_kizza_1", "pt_kizza", subMonths(now, 8), 9.4, 168, "Dr. Kansiime", "Started NPH 16 U nocte."),
    visit("vis_kizza_2", "pt_kizza", subMonths(now, 5), 8.9, 142, "Dr. Kansiime", "NPH titrated to 28 U."),
    visit("vis_kizza_3", "pt_kizza", subMonths(now, 2), 8.6, 118, "Dr. Atwine", "NPH 42 U. Fasting at target; A1c still high."),
    visit("vis_mugisha_1", "pt_mugisha", subMonths(now, 6), 6.8, 110, "Dr. Namanya", "Stable. 6-month review."),
    visit("vis_nalubega_1", "pt_nalubega", subMonths(now, 3), 8.6, 160, "Dr. Atwine", "ACR rising. Amlodipine only — needs ACEI."),
    visit("vis_tumusiime_1", "pt_tumusiime", subMonths(now, 4), 7.4, 136, "Sr. Kyohairwe", "Neuropathy symptoms. Eye exam overdue."),
    visit("vis_mwesigwa_1", "pt_mwesigwa", subMonths(now, 3), 7.8, 138, "Dr. Namanya", "Prior stroke. Statin not yet started."),
    visit("vis_kyomuhendo_1", "pt_kyomuhendo", subMonths(now, 4), 7.6, 140, "Dr. Kansiime", "Did not return for 3-month review."),
    visit("vis_wasswa_1", "pt_wasswa", subDays(now, 18), 7.9, 148, "Dr. Atwine", "Added gliclazide. Review in 4 weeks."),
    visit("vis_komugisha_1", "pt_komugisha", now, 7.1, 122, "Dr. Namanya", "At target. Discharged, 6-month review."),
  ];

  return { patients, visits };
}

function visit(
  id: string,
  patientId: string,
  date: Date,
  a1c: number,
  fpg: number,
  clinician: string,
  notes: string,
): Visit {
  return {
    id,
    patientId,
    date: iso(date),
    clinician,
    a1c,
    fpg,
    hypoglycemia: "none",
    symptomaticHyper: false,
    treatmentChanged: notes.toLowerCase().includes("start") || notes.toLowerCase().includes("added"),
    healthStatusChange: false,
    insulinStartedToday: notes.toLowerCase().includes("started nph"),
    smoking: false,
    alcohol: false,
    footExam: "deferred",
    neuropathyExam: "deferred",
    notes,
    meds: [],
    nextReview: iso(addDays(date, 90)),
    a1cIntervalMonths: 3,
    planSummary: notes,
    alerts: [],
  };
}

export const SEED_VERSION = 1;
