/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PatientsPatientIdRouteImport } from './routes/patients_.$patientId'
import { Route as PatientsNewRouteImport } from './routes/patients_.new'
import { Route as PatientsPatientIdVisitRouteImport } from './routes/patients_.$patientId_.visit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/patients_/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsNewRoute = PatientsNewRouteImport.update({
  id: '/patients_/new',
  path: '/patients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdVisitRoute = PatientsPatientIdVisitRouteImport.update({
  id: '/patients_/$patientId_/visit',
  path: '/patients/$patientId/visit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guidelines': typeof GuidelinesRoute
  '/patients': typeof PatientsRoute
  '/reviews': typeof ReviewsRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/patients/$patientId/visit': typeof PatientsPatientIdVisitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guidelines': typeof GuidelinesRoute
  '/patients': typeof PatientsRoute
  '/reviews': typeof ReviewsRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/patients/$patientId/visit': typeof PatientsPatientIdVisitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guidelines': typeof GuidelinesRoute
  '/patients': typeof PatientsRoute
  '/reviews': typeof ReviewsRoute
  '/patients_/$patientId': typeof PatientsPatientIdRoute
  '/patients_/new': typeof PatientsNewRoute
  '/patients_/$patientId_/visit': typeof PatientsPatientIdVisitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guidelines'
    | '/patients'
    | '/reviews'
    | '/patients/$patientId'
    | '/patients/new'
    | '/patients/$patientId/visit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guidelines'
    | '/patients'
    | '/reviews'
    | '/patients/$patientId'
    | '/patients/new'
    | '/patients/$patientId/visit'
  id:
    | '__root__'
    | '/'
    | '/guidelines'
    | '/patients'
    | '/reviews'
    | '/patients_/$patientId'
    | '/patients_/new'
    | '/patients_/$patientId_/visit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuidelinesRoute: typeof GuidelinesRoute
  PatientsRoute: typeof PatientsRoute
  ReviewsRoute: typeof ReviewsRoute
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
  PatientsNewRoute: typeof PatientsNewRoute
  PatientsPatientIdVisitRoute: typeof PatientsPatientIdVisitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients_/$patientId': {
      id: '/patients_/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients_/new': {
      id: '/patients_/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof PatientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients_/$patientId_/visit': {
      id: '/patients_/$patientId_/visit'
      path: '/patients/$patientId/visit'
      fullPath: '/patients/$patientId/visit'
      preLoaderRoute: typeof PatientsPatientIdVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuidelinesRoute: GuidelinesRoute,
  PatientsRoute: PatientsRoute,
  ReviewsRoute: ReviewsRoute,
  PatientsPatientIdRoute: PatientsPatientIdRoute,
  PatientsNewRoute: PatientsNewRoute,
  PatientsPatientIdVisitRoute: PatientsPatientIdVisitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
